### ISSUE TITLE
Call to undefined method MediaWiki\Extension\TemplateStyles\TemplateStylesMatcherFactory::cssSingleTimingFunction()

### ISSUE THREAD

**Issue by aolko** [octfx/mediawiki-extensions-TemplateStylesExtender#17]
[17c9655edffbb951dc922c17] /wiki/Special:Version Error: Call to undefined method MediaWiki\Extension\TemplateStyles\TemplateStylesMatcherFactory::cssSingleTimingFunction()

Backtrace:
```
from /home/admin/web/[redacted].wiki/public_html/extensions/TemplateStylesExtender/includes/TemplateStylesExtender.php(71)
#0 /home/admin/web/[redacted].wiki/public_html/extensions/TemplateStylesExtender/includes/Hooks/StylesheetSanitizerHook.php(62): MediaWiki\Extension\TemplateStylesExtender\TemplateStylesExtender->addVarSelector()
#1 /home/admin/web/[redacted].wiki/public_html/includes/HookContainer/HookContainer.php(161): MediaWiki\Extension\TemplateStylesExtender\Hooks\StylesheetSanitizerHook::onSanitize()
#2 /home/admin/web/[redacted].wiki/public_html/extensions/TemplateStyles/includes/Hooks/HookRunner.php(47): MediaWiki\HookContainer\HookContainer->run()
#3 /home/admin/web/[redacted].wiki/public_html/extensions/TemplateStyles/includes/Hooks.php(187): MediaWiki\Extension\TemplateStyles\Hooks\HookRunner->onTemplateStylesStylesheetSanitizer()
#4 /home/admin/web/[redacted].wiki/public_html/extensions/TemplateStyles/includes/TemplateStylesContentHandler.php(159): MediaWiki\Extension\TemplateStyles\Hooks::getSanitizer()
#5 /home/admin/web/[redacted].wiki/public_html/extensions/TemplateStyles/includes/Hooks.php(371): MediaWiki\Extension\TemplateStyles\TemplateStylesContentHandler->sanitize()
#6 /home/admin/web/[redacted].wiki/public_html/includes/parser/Parser.php(3943): MediaWiki\Extension\TemplateStyles\Hooks::handleTag()
#7 /home/admin/web/[redacted].wiki/public_html/includes/parser/PPFrame_Hash.php(352): Parser->extensionSubstitution()
#8 /home/admin/web/[redacted].wiki/public_html/includes/parser/Parser.php(2888): PPFrame_Hash->expand()
#9 /home/admin/web/[redacted].wiki/public_html/includes/parser/Parser.php(1544): Parser->replaceVariables()
#10 /home/admin/web/[redacted].wiki/public_html/includes/parser/Parser.php(651): Parser->internalParse()
#11 /home/admin/web/[redacted].wiki/public_html/includes/language/MessageCache.php(1505): Parser->parse()
#12 /home/admin/web/[redacted].wiki/public_html/includes/language/Message.php(1436): MessageCache->parse()
#13 /home/admin/web/[redacted].wiki/public_html/includes/language/Message.php(1006): Message->parseText()
#14 /home/admin/web/[redacted].wiki/public_html/includes/language/Message.php(1046): Message->format()
#15 /home/admin/web/[redacted].wiki/public_html/skins/Citizen/includes/SkinCitizen.php(105): Message->parse()
#16 /home/admin/web/[redacted].wiki/public_html/includes/skins/SkinMustache.php(92): MediaWiki\Skins\Citizen\SkinCitizen->getTemplateData()
#17 /home/admin/web/[redacted].wiki/public_html/includes/skins/SkinTemplate.php(174): SkinMustache->generateHTML()
#18 /home/admin/web/[redacted].wiki/public_html/includes/Output/OutputPage.php(2947): SkinTemplate->outputPage()
#19 /home/admin/web/[redacted].wiki/public_html/includes/MediaWiki.php(978): MediaWiki\Output\OutputPage->output()
#20 /home/admin/web/[redacted].wiki/public_html/includes/MediaWiki.php(613): MediaWiki->main()
#21 /home/admin/web/[redacted].wiki/public_html/index.php(50): MediaWiki->run()
#22 /home/admin/web/[redacted].wiki/public_html/index.php(46): wfIndexMain()
#23 {main}
```

**Comment by octfx** [comment]
I can't find any references to `cssSingleTimingFunction` in the current code base.  
- Which version of TemplateStylesExtender are you using?
- Which version of TemplateStyles is installed
- Which MW Version are you on?

**Comment by aolko** [comment]
> I can't find any references to `cssSingleTimingFunction` in the current code base.
> 
> * Which version of TemplateStylesExtender are you using?
> * Which version of TemplateStyles is installed
> * Which MW Version are you on?

- [d3b256f](https://github.com/octfx/mediawiki-extensions-TemplateStylesExtender/commit/d3b256f305e5d91b50b01a836c67e27d2a7b8331)
- latest
- 1.41.0
